### ISSUE TITLE
hashicorp hcl/hcl/printer dep error

### ISSUE THREAD

**Issue by themeadery** [kucoin-community-chain/kcc-toolkit#10]
Seems to be a dependency error. I don't know if the hashicorp repo changed since the last commit on this repo, but it's doing this:

`ubuntu@kcc:~$ go get github.com/kucoin-community-chain/kcc-toolkit
package github.com/hashicorp/hcl/hcl/printer: cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
        /usr/lib/go-1.10/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
        /home/ubuntu/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)`

**Comment by themeadery** [comment]
Issue is out of date go package in default Ubuntu apt repo.

Fix:
$ sudo add-apt-repository ppa:longsleep/golang-backports
$ sudo apt update
$ sudo apt install golang-go

**Comment by viaweb3** [comment]
merged
